title: Annie's Cafe
theme: jekyll-bulma
description: Über diese Seite... (max. 160 Zeichen)
url: 'https://annies.cafe'
sass:
  style: compressed
plugins:
  - jekyll-feed
collections:
  c:
    output: true

